name: valorant_guide_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  flutter_flavor: ^3.0.3
  logger: ^1.1.0
  hexcolor: ^2.0.7
  google_fonts: ^3.0.1
  flutter_launcher_icons: ^0.9.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

